In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/drive/MyDrive/admissionData (1) (1).csv')
df

admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

[400 rows x 4 columns]

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   admit   400 non-null    int64  
 1   gre     400 non-null    int64  
 2   gpa     400 non-null    float64
 3   rank    400 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 12.6 KB


In [4]:
df.shape

(400, 4)

In [5]:
df.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [6]:
df.isna().any()

admit    False
gre      False
gpa      False
rank     False
dtype: bool

In [7]:
x=df.iloc[:,1:4]
x

gre   gpa  rank
0    380  3.61     3
1    660  3.67     3
2    800  4.00     1
3    640  3.19     4
4    520  2.93     4
..   ...   ...   ...
395  620  4.00     2
396  560  3.04     3
397  460  2.63     2
398  700  3.65     2
399  600  3.89     3

[400 rows x 3 columns]

In [8]:
y=df['admit']
y

0      0
1      1
2      1
3      1
4      0
      ..
395    0
396    0
397    0
398    0
399    0
Name: admit, Length: 400, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [11]:
import sklearn.ensemble as ensm
adb= ensm.AdaBoostClassifier(n_estimators=10, learning_rate=1.0)
adb.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=10)

In [12]:
ypred= adb.predict(x_test)
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [13]:
trainingscore=adb.score(x_train,y_train)
trainingscore

0.71875

In [14]:
testingscore=adb.score(x_test,y_test)
testingscore

0.6875

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,ypred)

0.6875

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,ypred)

array([[47,  8],
       [17,  8]])

example 2:

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/drive/MyDrive/kc1_csv (1) (1).csv')
df

loc  v(g)  ev(g)  iv(g)      n       v     l      d      i         e  \
0      1.1   1.4    1.4    1.4    1.3    1.30  1.30   1.30   1.30      1.30   
1      1.0   1.0    1.0    1.0    1.0    1.00  1.00   1.00   1.00      1.00   
2     83.0  11.0    1.0   11.0  171.0  927.89  0.04  23.04  40.27  21378.61   
3     46.0   8.0    6.0    8.0  141.0  769.78  0.07  14.86  51.81  11436.73   
4     25.0   3.0    1.0    3.0   58.0  254.75  0.11   9.35  27.25   2381.95   
...    ...   ...    ...    ...    ...     ...   ...    ...    ...       ...   
2104  19.0   2.0    1.0    2.0   40.0  175.69  0.15   6.82  25.77   1197.90   
2105  23.0   3.0    3.0    3.0   60.0  278.63  0.10   9.69  28.75   2700.58   
2106   2.0   1.0    1.0    1.0    4.0    8.00  0.67   1.50   5.33     12.00   
2107  13.0   1.0    1.0    1.0   17.0   60.94  0.25   4.00  15.24    243.78   
2108  11.0   2.0    1.0    2.0   27.0  102.80  0.17   6.00  17.13    616.79   

      ...  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0     ...       2          2        2                  2      1.2        1.2   
1     ...       1          1        1                  1      1.0        1.0   
2     ...      65         10        6                  0     18.0       25.0   
3     ...      37          2        5                  0     16.0       28.0   
4     ...      21          0        2                  0     11.0       10.0   
...   ...     ...        ...      ...                ...      ...        ...   
2104  ...      12          1        2                  0     10.0       11.0   
2105  ...      18          1        2                  0     12.0       13.0   
2106  ...       0          0        0                  0      3.0        1.0   
2107  ...       6          0        5                  0      6.0        6.0   
2108  ...       9          0        0                  0      8.0        6.0   

      total_Op  total_Opnd  branchCount  defects  
0          1.2         1.2          1.4    False  
1          1.0         1.0          1.0     True  
2        107.0        64.0         21.0     True  
3         89.0        52.0         15.0     True  
4         41.0        17.0          5.0     True  
...        ...         ...          ...      ...  
2104      25.0        15.0          3.0    False  
2105      39.0        21.0          5.0    False  
2106       3.0         1.0          1.0    False  
2107       9.0         8.0          1.0    False  
2108      18.0         9.0          3.0    False  

[2109 rows x 22 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2109 entries, 0 to 2108
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   loc                2109 non-null   float64
 1   v(g)               2109 non-null   float64
 2   ev(g)              2109 non-null   float64
 3   iv(g)              2109 non-null   float64
 4   n                  2109 non-null   float64
 5   v                  2109 non-null   float64
 6   l                  2109 non-null   float64
 7   d                  2109 non-null   float64
 8   i                  2109 non-null   float64
 9   e                  2109 non-null   float64
 10  b                  2109 non-null   float64
 11  t                  2109 non-null   float64
 12  lOCode             2109 non-null   int64  
 13  lOComment          2109 non-null   int64  
 14  lOBlank            2109 non-null   int64  
 15  locCodeAndComment  2109 non-null   int64  
 16  uniq_Op            2109 

In [19]:
df.shape

(2109, 22)

In [20]:
df.dtypes

loc                  float64
v(g)                 float64
ev(g)                float64
iv(g)                float64
n                    float64
v                    float64
l                    float64
d                    float64
i                    float64
e                    float64
b                    float64
t                    float64
lOCode                 int64
lOComment              int64
lOBlank                int64
locCodeAndComment      int64
uniq_Op              float64
uniq_Opnd            float64
total_Op             float64
total_Opnd           float64
branchCount          float64
defects                 bool
dtype: object

In [21]:
df.isnull().sum()

loc                  0
v(g)                 0
ev(g)                0
iv(g)                0
n                    0
v                    0
l                    0
d                    0
i                    0
e                    0
b                    0
t                    0
lOCode               0
lOComment            0
lOBlank              0
locCodeAndComment    0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64

In [22]:
df.isna().any()

loc                  False
v(g)                 False
ev(g)                False
iv(g)                False
n                    False
v                    False
l                    False
d                    False
i                    False
e                    False
b                    False
t                    False
lOCode               False
lOComment            False
lOBlank              False
locCodeAndComment    False
uniq_Op              False
uniq_Opnd            False
total_Op             False
total_Opnd           False
branchCount          False
defects              False
dtype: bool

In [23]:
df=df.drop_duplicates()

In [24]:
df

loc  v(g)  ev(g)  iv(g)      n       v     l      d      i         e  \
0      1.1   1.4    1.4    1.4    1.3    1.30  1.30   1.30   1.30      1.30   
1      1.0   1.0    1.0    1.0    1.0    1.00  1.00   1.00   1.00      1.00   
2     83.0  11.0    1.0   11.0  171.0  927.89  0.04  23.04  40.27  21378.61   
3     46.0   8.0    6.0    8.0  141.0  769.78  0.07  14.86  51.81  11436.73   
4     25.0   3.0    1.0    3.0   58.0  254.75  0.11   9.35  27.25   2381.95   
...    ...   ...    ...    ...    ...     ...   ...    ...    ...       ...   
2102  14.0   2.0    1.0    2.0   28.0  109.39  0.19   5.14  21.27    562.59   
2104  19.0   2.0    1.0    2.0   40.0  175.69  0.15   6.82  25.77   1197.90   
2105  23.0   3.0    3.0    3.0   60.0  278.63  0.10   9.69  28.75   2700.58   
2107  13.0   1.0    1.0    1.0   17.0   60.94  0.25   4.00  15.24    243.78   
2108  11.0   2.0    1.0    2.0   27.0  102.80  0.17   6.00  17.13    616.79   

      ...  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  uniq_Opnd  \
0     ...       2          2        2                  2      1.2        1.2   
1     ...       1          1        1                  1      1.0        1.0   
2     ...      65         10        6                  0     18.0       25.0   
3     ...      37          2        5                  0     16.0       28.0   
4     ...      21          0        2                  0     11.0       10.0   
...   ...     ...        ...      ...                ...      ...        ...   
2102  ...      11          0        1                  0      8.0        7.0   
2104  ...      12          1        2                  0     10.0       11.0   
2105  ...      18          1        2                  0     12.0       13.0   
2107  ...       6          0        5                  0      6.0        6.0   
2108  ...       9          0        0                  0      8.0        6.0   

      total_Op  total_Opnd  branchCount  defects  
0          1.2         1.2          1.4    False  
1          1.0         1.0          1.0     True  
2        107.0        64.0         21.0     True  
3         89.0        52.0         15.0     True  
4         41.0        17.0          5.0     True  
...        ...         ...          ...      ...  
2102      19.0         9.0          3.0    False  
2104      25.0        15.0          3.0    False  
2105      39.0        21.0          5.0    False  
2107       9.0         8.0          1.0    False  
2108      18.0         9.0          3.0    False  

[1212 rows x 22 columns]

In [25]:
df.shape

(1212, 22)

In [26]:
x=df.drop(['defects'],axis=1)
x

loc  v(g)  ev(g)  iv(g)      n       v     l      d      i         e  \
0      1.1   1.4    1.4    1.4    1.3    1.30  1.30   1.30   1.30      1.30   
1      1.0   1.0    1.0    1.0    1.0    1.00  1.00   1.00   1.00      1.00   
2     83.0  11.0    1.0   11.0  171.0  927.89  0.04  23.04  40.27  21378.61   
3     46.0   8.0    6.0    8.0  141.0  769.78  0.07  14.86  51.81  11436.73   
4     25.0   3.0    1.0    3.0   58.0  254.75  0.11   9.35  27.25   2381.95   
...    ...   ...    ...    ...    ...     ...   ...    ...    ...       ...   
2102  14.0   2.0    1.0    2.0   28.0  109.39  0.19   5.14  21.27    562.59   
2104  19.0   2.0    1.0    2.0   40.0  175.69  0.15   6.82  25.77   1197.90   
2105  23.0   3.0    3.0    3.0   60.0  278.63  0.10   9.69  28.75   2700.58   
2107  13.0   1.0    1.0    1.0   17.0   60.94  0.25   4.00  15.24    243.78   
2108  11.0   2.0    1.0    2.0   27.0  102.80  0.17   6.00  17.13    616.79   

      ...        t  lOCode  lOComment  lOBlank  locCodeAndComment  uniq_Op  \
0     ...     1.30       2          2        2                  2      1.2   
1     ...     1.00       1          1        1                  1      1.0   
2     ...  1187.70      65         10        6                  0     18.0   
3     ...   635.37      37          2        5                  0     16.0   
4     ...   132.33      21          0        2                  0     11.0   
...   ...      ...     ...        ...      ...                ...      ...   
2102  ...    31.26      11          0        1                  0      8.0   
2104  ...    66.55      12          1        2                  0     10.0   
2105  ...   150.03      18          1        2                  0     12.0   
2107  ...    13.54       6          0        5                  0      6.0   
2108  ...    34.27       9          0        0                  0      8.0   

      uniq_Opnd  total_Op  total_Opnd  branchCount  
0           1.2       1.2         1.2          1.4  
1           1.0       1.0         1.0          1.0  
2          25.0     107.0        64.0         21.0  
3          28.0      89.0        52.0         15.0  
4          10.0      41.0        17.0          5.0  
...         ...       ...         ...          ...  
2102        7.0      19.0         9.0          3.0  
2104       11.0      25.0        15.0          3.0  
2105       13.0      39.0        21.0          5.0  
2107        6.0       9.0         8.0          1.0  
2108        6.0      18.0         9.0          3.0  

[1212 rows x 21 columns]

In [27]:
y=df['defects']
y

0       False
1        True
2        True
3        True
4        True
        ...  
2102    False
2104    False
2105    False
2107    False
2108    False
Name: defects, Length: 1212, dtype: bool

In [28]:
df.defects.unique()

array([False,  True])

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 1, ..., 0, 0, 0])

In [30]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20)



In [31]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
xtrain = sd.fit_transform(xtrain)
xtest = sd.fit_transform(xtest)

In [32]:
from xgboost import XGBClassifier

In [33]:
from sklearn.metrics import accuracy_score


In [34]:
model1 = XGBClassifier()
model1.fit(xtrain,ytrain)


AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)